[2021-11-14 17:21:30 +0545] [512311] [INFO] Starting gunicorn 20.1.0
[2021-11-14 17:21:30 +0545] [512311] [INFO] Listening at: http://127.0.0.1:8000 (512311)
[2021-11-14 17:21:30 +0545] [512311] [INFO] Using worker: sync
[2021-11-14 17:21:30 +0545] [512344] [INFO] Booting worker with pid: 512344
[2021-11-14 17:21:30 +0545] [512344] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/rikeshkarma/.local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/rikeshkarma/.local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/rikeshkarma/.local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/rikeshkarma/.local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/rikeshkarma/.local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/rikeshkarma/.local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/rikeshkarma/.local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app_py'
[2021-11-14 17:21:30 +0545] [512344] [INFO] Worker exiting (pid: 512344)
[2021-11-14 17:21:30 +0545] [512311] [INFO] Shutting down: Master
[2021-11-14 17:21:30 +0545] [512311] [INFO] Reason: Worker failed to boot.
